--SELECT COUNT(*), ID_ORIG_H,--- ID_ORIG_P, PROTO, SERVICE,
--COUNT( DISTINCT PROTO),
--COUNT( DISTINCT SERVICE),
--COUNT( DISTINCT ID_ORIG_P),
--COUNT( DISTINCT ID_RESP_H),
--COUNT( DISTINCT ID_RESP_P),
--SUM(DURATION),  
--SUM(ORIG_PKTS), 
--SUM(ORIG_BYTES),
--SUM(RESP_PKTS) ,
--SUM(RESP_BYTES)
--FROM JSON00
--WHERE tipo = 'CONN'
--AND TS_CODE >= TO_TIMESTAMP ('2018-12-02 23:57:15.000')
--
--GROUP BY ID_ORIG_H;
SELECT COUNT(*), PROTO,--- ID_ORIG_P, PROTO, SERVICE,
--COUNT( DISTINCT PROTO),
SUM(DURATION),  
--SUM(ORIG_PKTS), 
--SUM(ORIG_BYTES),
--SUM(RESP_PKTS) ,
SUM(RESP_BYTES)
FROM JSON00
WHERE tipo = 'CONN'
AND TS_CODE >= TO_TIMESTAMP ('2018-12-02 23:57:15.000')
GROUP BY PROTO;
