CREATE VIEW "LOGOLD" ( pk VARCHAR PRIMARY KEY, 
"key"."ts" 		          VARCHAR,
"key"."uid" 	          VARCHAR,
"key"."idOrigH"           VARCHAR,                              
"key"."idOrigP"           VARCHAR,                              
"key"."idRespH"           VARCHAR,                              
"key"."idRespP"           VARCHAR,                              
"dns"."query"             VARCHAR,
"dns"."proto"             VARCHAR,
"dns"."trans_id"          VARCHAR,
"conn"."proto"		      VARCHAR,
"conn"."service"          VARCHAR,
"conn"."duration"         VARCHAR,
"conn"."orig_bytes"       VARCHAR,
"conn"."resp_bytes"       VARCHAR,
"conn"."conn_state"       VARCHAR,
"conn"."orig_pkts"        VARCHAR,
"conn"."orig_ip_bytes"    VARCHAR,
"conn"."resp_pkts"        VARCHAR,
"conn"."resp_ip_bytes"    VARCHAR,
"http"."request_body_len" VARCHAR,
"http"."response_body_len"VARCHAR,
"http"."status_code"      VARCHAR,
"http"."status_msg"       VARCHAR,
"http"."resp_fuids"       VARCHAR
);
