SELECT --COUNT (*)--PROTO, COUNT--COUNT(*)
COUNT,    
--PROTO,    
--SERVICE,  
ID_ORIG_H
--ID_ORIG_P,
--ID_RESP_H
FROM LOG_TOTAIS
WHERE TIPO = 'ORIG_H';
--AND ("SUM(ORIG_PKTS)"  IS NULL 
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(RESP_BYTES)" IS NULL);

--WHERE ID_RESP_H IS NULL
--AND PROTO = 'tcp'
--AND SERVICE = 'ssl';

