SELECT --COUNT (*)--PROTO, COUNT--COUNT(*)
TO_DATE(TS_CODE, 'yyyy-MM-dd', 'GMT+2'),
SERVICE,
ID_RESP_H
--COUNT 
--PROTO,    
--SERVICE,  

--ID_ORIG_P,
--ID_RESP_H
FROM LOG_TOTAIS
WHERE TIPO = 'RESP_H_SERVICE'
AND SERVICE = 'http';
--ORDER BY COUNT;
--AND ("SUM(ORIG_PKTS)"  IS NULL 
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(RESP_BYTES)" IS NULL);

--WHERE ID_RESP_H IS NULL
--AND PROTO = 'tcp'
--AND SERVICE = 'ssl';

