SELECT COUNT (*)--PROTO, COUNT--COUNT(*)
--TIPO,      
--TS_FILTRO,
--TS_CODE,	  
--COUNT,     
--PROTO     
--ORIG_PKTS, 
--ORIG_BYTES
--RESP_PKTS, 
--RESP_BYTES
--PROTO,
--ID_ORIG_H,
--ID_ORIG_P,
--"SUM(ORIG_PKTS)", 
--"SUM(ORIG_BYTES)",
--"SUM(ORIG_BYTES)",
--"SUM(RESP_BYTES)"
FROM LOG_ANALYZES2
where TIPO = 'ORIG_H_P'
AND COUNT is NULL;
--AND ("SUM(ORIG_PKTS)"  IS NULL 
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(ORIG_BYTES)" IS NULL  
--OR   "SUM(RESP_BYTES)" IS NULL);

--WHERE ID_RESP_H IS NULL
--AND PROTO = 'tcp'
--AND SERVICE = 'ssl';

