CREATE TABLE IF NOT EXISTS IP_INFO (            

	IP 			VARCHAR,
	
	TS_CODE     TIMESTAMP,
	HOSTNAME 	VARCHAR, 
    CITY 		VARCHAR,
    REGION 		VARCHAR,
    COUNTRY 	VARCHAR,
    ORG 		VARCHAR,
    LATITUDE 	DOUBLE,
    LONGITUDE 	DOUBLE 

CONSTRAINT PK PRIMARY KEY(IP));

